#!/usr/bin/env node
/**
 * DEDUPLICATE THE IMAGE POOL — without touching the inventory.
 *
 * The Loggia CDN served the same photograph under many different hashes: 872
 * files in `public/images`, **713 of them distinct**, and one photograph
 * present under ten separate names. 159 redundant files, **104.6 MB** of
 * byte-identical bytes, in a repository that is 445 MB packed.
 *
 * The obvious fix — rewrite every reference to a canonical hash and delete the
 * rest — would edit `content/`, and `content/` is the Phase 0 record of what
 * the legacy site served. That a photograph was published under ten URLs is
 * itself a fact about the old site, and this project does not edit the record
 * to tidy the repository.
 *
 * So the record stays and the BYTES go. This writes an alias map, `localImage()`
 * consults it, and the redundant files are deleted. Every legacy hash still
 * resolves — through the resolver instead of through a duplicate file.
 *
 * The canonical file in each group is chosen by sorted filename, so the choice
 * is stable across runs and across machines: a dedupe whose output depends on
 * directory order would produce a different map every time it ran.
 *
 *   node scripts/dedupe-images.mjs --dry     report only
 *   node scripts/dedupe-images.mjs           write the map and delete
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const DRY = process.argv.includes("--dry");
const ROOT = process.cwd();
const DIRS = ["public/images/_pool", "public/images/_chh", "public/images/_site"];
const OUT = path.join(ROOT, "content", "image-aliases.json");

const byHash = new Map();
let totalBytes = 0;
let totalFiles = 0;

for (const d of DIRS) {
  const dir = path.join(ROOT, d);
  if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir).sort()) {
    const p = path.join(dir, f);
    const st = fs.statSync(p);
    if (!st.isFile()) continue;
    totalBytes += st.size;
    totalFiles++;
    const h = crypto.createHash("sha1").update(fs.readFileSync(p)).digest("hex");
    if (!byHash.has(h)) byHash.set(h, []);
    byHash.get(h).push({ web: `/${d.replace(/^public\//, "")}/${f}`, abs: p, size: st.size });
  }
}

const aliases = {};
let reclaimed = 0;
let removed = 0;
let groups = 0;

for (const [, list] of byHash) {
  if (list.length < 2) continue;
  groups++;
  /* Stable canonical: the first by web path once sorted. */
  const sorted = [...list].sort((a, b) => (a.web < b.web ? -1 : 1));
  const canonical = sorted[0];
  for (const dup of sorted.slice(1)) {
    aliases[dup.web] = canonical.web;
    reclaimed += dup.size;
    removed++;
    if (!DRY) fs.unlinkSync(dup.abs);
  }
}

if (!DRY) {
  fs.writeFileSync(
    OUT,
    JSON.stringify(
      {
        _comment: [
          "GENERATED by scripts/dedupe-images.mjs — do not edit by hand.",
          "",
          "The legacy CDN served the same photograph under many hashes. The files were",
          "byte-identical, so only one copy of each is kept on disk and every other",
          "address resolves to it here.",
          "",
          "content/ is NOT rewritten. That a photograph was published under ten URLs is",
          "a fact about the old site and belongs in the Phase 0 record; this map is how",
          "the record stays true while the repository stops carrying the bytes.",
          "",
          "`localImage()` in src/lib/content.ts consults this, so a blocked or aliased",
          "address cannot bypass it. tests/images.spec.ts asserts every alias target",
          "exists on disk and that nothing referenced anywhere resolves to a missing",
          "file.",
        ],
        aliases,
      },
      null,
      2
    ) + "\n"
  );
}

const mb = (b) => (b / 1048576).toFixed(1);
console.log(`${totalFiles} files, ${byHash.size} distinct, ${mb(totalBytes)} MB`);
console.log(`${groups} duplicate groups, ${removed} redundant files, ${mb(reclaimed)} MB reclaimable`);
console.log(DRY ? "\n(dry run — nothing written, nothing deleted)" : `\n-> ${path.relative(ROOT, OUT)}`);
