#!/usr/bin/env node
/**
 * IS ANY FLAGGED PHOTOGRAPH ACTUALLY ON THE SITE?
 *
 * The grading pass flagged 109 frames: 23 as stock, 22 as a public place, 1 as a
 * different property, 63 as unsure. A flag is not a quality judgement — it is a
 * claim that the photograph may not be THIS property.
 *
 * That matters more here than it would anywhere else. **This entire project
 * exists because the previous site used stock photographs of places that were
 * not Thalasses, and the owner found out.** A flagged frame sitting on the
 * rebuild would be the same failure with better typography.
 *
 * So the question is not "how many did we flag" but "how many did we ship", and
 * nothing else in the suite can answer it: the grading pass knows which frames
 * are suspect and the site knows which frames it renders, and until now those
 * two facts had never been put in the same room.
 *
 *   node scripts/flagged-on-site.mjs
 */
import { chromium } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const BASE = process.env.CAPTURE_BASE ?? "http://localhost:3005";
const OUT = path.join(ROOT, "qa", "looks");
fs.mkdirSync(OUT, { recursive: true });

async function reachable(url) {
  for (let i = 0; i < 20; i++) {
    try {
      const r = await fetch(url, { method: "HEAD" });
      if (r.status < 500) return true;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
  return false;
}
if (!(await reachable(BASE))) {
  console.error(`No server at ${BASE}. Run \`npm start\` first.`);
  process.exit(1);
}

const gradesFile = path.join(ROOT, "content", "photo-grades.json");
if (!fs.existsSync(gradesFile)) {
  console.error("content/photo-grades.json is missing — run the grading pass first.");
  process.exit(1);
}
const grades = JSON.parse(fs.readFileSync(gradesFile, "utf-8"));
const flagged = new Map(grades.frames.filter((f) => f.flag).map((f) => [f.path, f]));

/* Phase 1's flags too — they were recorded and never cross-checked either. */
const selects = JSON.parse(fs.readFileSync(path.join(ROOT, "content", "photo-selects.json"), "utf-8"));
const byN = new Map(selects.selects.map((s) => [s.n, s]));
for (const f of selects.flags) {
  const s = byN.get(f.n);
  if (s?.path && !flagged.has(s.path)) {
    flagged.set(s.path, { path: s.path, subject: s.subject, flag: f.concern, flagReason: f.reason, pass: 1 });
  }
}

const ROUTES = [
  "/",
  "/en/the-estate",
  "/en/villas/villa-thoi",
  "/en/villas/villa-persi",
  "/en/villas/villa-eeanthe",
  "/en/villas/villa-melia",
  "/en/villas/villa-pueblo",
  "/en/gallery",
  "/en/experiences",
  "/en/weddings",
  "/en/location",
  "/en/contact",
  "/en/careers",
];

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });

const hits = new Map();
for (const route of ROUTES) {
  await page.goto(BASE + route, { waitUntil: "load", timeout: 90_000 });
  const total = await page.evaluate(() => document.body.scrollHeight);
  for (let y = 0; y <= total; y += 800) {
    await page.evaluate((v) => window.scrollTo(0, v), y);
    await page.waitForTimeout(30);
  }
  /* next/image rewrites src to /_next/image?url=… — unwrap to the real path. */
  const srcs = await page.evaluate(() =>
    [...document.querySelectorAll("img")].map((i) => {
      const s = i.getAttribute("src") ?? "";
      const m = /url=([^&]+)/.exec(s);
      return m ? decodeURIComponent(m[1]) : s;
    })
  );
  for (const s of new Set(srcs)) {
    if (!s.startsWith("/images/")) continue;
    if (flagged.has(s)) {
      if (!hits.has(s)) hits.set(s, []);
      hits.get(s).push(route);
    }
  }
}
await browser.close();

const rows = [...hits].map(([src, routes]) => ({ ...flagged.get(src), src, routes }));
const hard = rows.filter((r) => r.flag !== "unsure");
const soft = rows.filter((r) => r.flag === "unsure");

const byKind = {};
for (const r of rows) byKind[r.flag] = (byKind[r.flag] ?? 0) + 1;

let md = `# Flagged photographs that the site actually renders

Generated by \`npm run flagged\`. Cross-references the grading passes against what
the built site puts on a page.

**${flagged.size} frames carry a flag. ${rows.length} of them are rendered by the site.**

A flag is not a quality judgement. It is a claim that the photograph may not be
this property — and this project exists because the previous site used stock
photographs of places that were not Thalasses. A flagged frame on the rebuild
would be the same failure with better typography.

| flag | on the site |
|---|---|
${Object.entries(byKind)
  .map(([k, v]) => `| \`${k}\` | ${v} |`)
  .join("\n")}

## The ${hard.length} that are not merely "unsure"

These carry a specific claim — stock, a public place, or a different property.
**Each one needs an owner ruling before launch.**

${
  hard.length
    ? hard
        .map(
          (r) =>
            `### \`${r.flag}\` — ${r.subject}\n\n` +
            `- \`${r.src}\`\n` +
            `- On: ${r.routes.map((x) => `\`${x}\``).join(", ")}\n` +
            `- Why: ${r.flagReason ?? "(no reason recorded)"}\n`
        )
        .join("\n")
    : "None. Every frame the site renders is either unflagged or only marked `unsure`.\n"
}

## The ${soft.length} marked \`unsure\`

A grader could not tell whether these are this property. They are not
necessarily wrong — several are shoreline and garden frames with no building in
shot — but each is a question only the owner can close.

${soft.map((r) => `- ${r.subject} — \`${r.src}\` (${r.routes.join(", ")})`).join("\n") || "None."}
`;

fs.writeFileSync(path.join(OUT, "FLAGGED-ON-SITE.md"), md);
fs.writeFileSync(path.join(OUT, "flagged-on-site.json"), JSON.stringify(rows, null, 2) + "\n");

/* ------------------------------------------------------------ quarantine -- */
/**
 * THE RATCHET.
 *
 * These frames are not deleted here, and that is deliberate: the standing rule
 * of this project is that content is kept and reorganised, never removed, and
 * which photographs represent the property is the owner's call, not mine.
 *
 * But "the owner has not ruled yet" must not quietly become "nobody is
 * watching". So the ones found today are written down, with the grader's reason
 * and every route they appear on, and `tests/flagged.spec.ts` fails the build if
 * the site ever renders a hard-flagged frame that is NOT on this list.
 *
 * The existing ones are held pending a ruling. A new one stops a push.
 */
const QUARANTINE = path.join(ROOT, "content", "flagged-quarantine.json");
if (process.argv.includes("--adopt")) {
  fs.writeFileSync(
    QUARANTINE,
    JSON.stringify(
      {
        _note:
          "Flagged photographs the site currently renders, held pending an OWNER RULING. " +
          "Nothing here has been deleted — content decisions belong to the owner and this " +
          "project keeps what it is given. `tests/flagged.spec.ts` fails if a hard-flagged " +
          "frame appears that is not on this list, so the count can shrink and never grow " +
          "by accident. Regenerate with `npm run flagged -- --adopt` and read the diff.",
        _whyItMatters:
          "This rebuild exists because the previous site used stock photographs of places " +
          "that were not Thalasses. A flagged frame shipping here would be the same failure " +
          "with better typography.",
        status: "owner-pending",
        frames: rows
          .filter((r) => r.flag !== "unsure")
          .map((r) => ({ src: r.src, flag: r.flag, subject: r.subject, why: r.flagReason, routes: r.routes })),
        unsure: soft.map((r) => ({ src: r.src, subject: r.subject, routes: r.routes })),
      },
      null,
      2
    ) + "\n"
  );
  console.log(`quarantine adopted: ${hard.length} hard-flagged, ${soft.length} unsure -> content/flagged-quarantine.json`);
}

console.log(`${flagged.size} flagged frames known; ${rows.length} are rendered by the site`);
console.log(`  ${hard.length} carry a specific claim (stock / public-place / different-property)`);
console.log(`  ${soft.length} are "unsure"`);
console.log(byKind);
console.log(`-> qa/looks/FLAGGED-ON-SITE.md`);
