#!/usr/bin/env node
/**
 * MEDIA AND REPOSITORY WEIGHT.
 *
 * A luxury villa site is mostly photographs, so weight is not a tidiness
 * question — it is the deploy time, the clone time, and the thing that decides
 * whether the next person can work on this comfortably.
 *
 * Measured from what git actually tracks, not from what is on disk: an ignored
 * file costs a developer nothing and costs a deployment nothing.
 *
 *   node scripts/media-weight.mjs
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "MEDIA-WEIGHT.md");

const tracked = execSync("git ls-files", { cwd: ROOT, maxBuffer: 64 * 1024 * 1024 })
  .toString()
  .split("\n")
  .map((s) => s.trim())
  .filter(Boolean);

const byDir = new Map();
const files = [];
let total = 0;
for (const f of tracked) {
  let size = 0;
  try {
    size = fs.statSync(path.join(ROOT, f)).size;
  } catch {
    continue; /* staged deletion */
  }
  total += size;
  files.push({ f, size });
  const dir = f.includes("/") ? f.split("/").slice(0, 2).join("/") : "(root)";
  byDir.set(dir, (byDir.get(dir) ?? 0) + size);
}

const mb = (b) => (b / 1048576).toFixed(1);
const rows = [...byDir.entries()].sort((a, b) => b[1] - a[1]).slice(0, 14);
const biggest = files.sort((a, b) => b.size - a.size).slice(0, 10);

/* Image stores, and how much duplication is left in them. */
const aliases = fs.existsSync(path.join(ROOT, "content", "image-aliases.json"))
  ? Object.keys(
      JSON.parse(fs.readFileSync(path.join(ROOT, "content", "image-aliases.json"), "utf-8")).aliases
    ).length
  : 0;

const stores = ["_pool", "_chh", "_site"].map((s) => {
  const dir = path.join(ROOT, "public", "images", s);
  if (!fs.existsSync(dir)) return { s, n: 0, bytes: 0 };
  const list = fs.readdirSync(dir);
  return {
    s,
    n: list.length,
    bytes: list.reduce((n, f) => n + fs.statSync(path.join(dir, f)).size, 0),
  };
});

const md = `# Media and repository weight

Generated by \`npm run weight\`. Measured from what **git tracks**, not from what
is on disk — an ignored file costs a developer and a deployment nothing.

**${mb(total)} MB tracked, across ${files.length} files.**

## By directory

| path | size |
|---|---|
${rows.map(([d, b]) => `| \`${d}\` | ${mb(b)} MB |`).join("\n")}

## The photography

| store | files | size |
|---|---|---|
${stores.map((s) => `| \`public/images/${s.s}\` | ${s.n} | ${mb(s.bytes)} MB |`).join("\n")}

**${aliases} addresses resolve to a shared file** rather than to a copy of their
own. The legacy CDN served the same photograph under many hashes — one of them
under ten — and the duplicates were byte-identical. \`npm run dedupe\` removed
**159 redundant files, 104.6 MB**, and \`content/image-aliases.json\` keeps every
legacy address working.

\`content/\` was **not** rewritten to a canonical hash. That a photograph was
published under ten URLs is a fact about the old site and belongs in the Phase 0
record. The record stays; the bytes went.

## The ten largest tracked files

| file | size |
|---|---|
${biggest.map((b) => `| \`${b.f}\` | ${mb(b.size)} MB |`).join("\n")}

## What is deliberately not tracked

Evidence follows a rule rather than a list of exceptions:

- **Regenerable evidence is not committed.** \`npm run capture\`,
  \`npm run capture:composites\` and \`npm run taste\` rebuild the walkthrough
  stills, the videos, the composites and the audit in minutes from committed
  source. Carrying them doubled the repository for pictures anyone can remake.
- **Spent evidence is not committed.** The A/B/C bake-off screenshots recorded a
  decision the owner has since made; the decision lives in the documents.
- **Decision evidence stays.** \`qa/greek-face\` (the T-189 verdict nobody has
  ruled on yet), \`qa/curation\` (frames awaiting an owner ruling), and every
  markdown report. Small, and each is waiting on a person.

## The honest limit of this

Untracking a file and deleting a duplicate shrink the **working tree** and every
shallow clone — which is what a Vercel build does. They do **not** shrink the
packed history: git still holds the old blobs, and only rewriting history would
remove them.

**History is deliberately not being rewritten.** The repository is public and
pushed; a rewrite breaks every existing clone, and this project has already done
one under duress during the credential incident. The cost of carrying the old
blobs is paid once per full clone; the cost of a second rewrite is paid by
everyone who has the repository now.
`;

fs.writeFileSync(OUT, md);
console.log(`${mb(total)} MB tracked across ${files.length} files`);
for (const [d, b] of rows.slice(0, 6)) console.log(`  ${mb(b).padStart(7)} MB  ${d}`);
console.log(`\n-> ${path.relative(ROOT, OUT)}`);
